apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: evo-todo
  namespace: evo-todo
  labels:
    app.kubernetes.io/name: evo-todo
    app.kubernetes.io/component: frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: evo-todo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: evo-todo
                port:
                  name: http
