apiVersion: v1
kind: Service
metadata:
  name: evo-todo
  namespace: evo-todo
  labels:
    app.kubernetes.io/name: evo-todo
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app: evo-todo
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
