apiVersion: v1
kind: Service
metadata:
  name: {{ include "evo-todo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "evo-todo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "evo-todo.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
